get http://localhost:3000/movies/

###
POST http://localhost:3000/movies/ 
Content-Type: application/json

{
    "directorId":6,
    "movieName": "Jurassic Park",
    "leadActor": "Jeff Goldblum"
}

###
GET http://localhost:3000/movies/121/


###
PUT http://localhost:3000/movies/121/
Content-Type: application/json


{
    "directorId": 24,
    "movieName": "Thor",
    "leadActor":"Chirstopher Hemsworth"
}


###
DELETE http://localhost:3000/movies/24/

###
GET http://localhost:3000/directors/

###
GET http://localhost:3000/directors/2/movies/